# Generated by Django 5.2.14 on 2026-07-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zoom_user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
