# Generated by Django 5.2.14 on 2026-07-23 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_bio_userprofile_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAssignmentQueueEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Coach assignment queue entry',
                'verbose_name_plural': 'Coach assignment queue',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.userprofile',),
        ),
        migrations.CreateModel(
            name='ClientOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(max_length=64)),
                ('morning_window', models.CharField(choices=[('6-8am', '6:00–8:00 am'), ('8-10am', '8:00–10:00 am'), ('10am-12pm', '10:00 am–12:00 pm')], max_length=20)),
                ('evening_window', models.CharField(choices=[('4-6pm', '4:00–6:00 pm'), ('6-8pm', '6:00–8:00 pm'), ('8-10pm', '8:00–10:00 pm')], max_length=20)),
                ('contact_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS')], max_length=10)),
                ('contact_number', models.CharField(max_length=30)),
                ('help_topics', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_onboarding', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
