# Generated by Django 5.2.14 on 2026-07-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_coachassignmentqueueentry_clientonboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
