# Generated by Django 5.2.14 on 2026-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_terms_accepted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientonboarding',
            name='evening_window',
            field=models.CharField(choices=[('4-5pm', '4:00–5:00 pm'), ('5-6pm', '5:00–6:00 pm'), ('6-7pm', '6:00–7:00 pm'), ('7-8pm', '7:00–8:00 pm'), ('8-9pm', '8:00–9:00 pm'), ('9-10pm', '9:00–10:00 pm'), ('4-6pm', '4:00–6:00 pm'), ('6-8pm', '6:00–8:00 pm'), ('8-10pm', '8:00–10:00 pm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientonboarding',
            name='morning_window',
            field=models.CharField(choices=[('6-7am', '6:00–7:00 am'), ('7-8am', '7:00–8:00 am'), ('8-9am', '8:00–9:00 am'), ('9-10am', '9:00–10:00 am'), ('10-11am', '10:00–11:00 am'), ('11am-12pm', '11:00 am–12:00 pm'), ('6-8am', '6:00–8:00 am'), ('8-10am', '8:00–10:00 am'), ('10am-12pm', '10:00 am–12:00 pm')], max_length=20),
        ),
    ]
