# Generated by Django 5.2.14 on 2026-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_clientonboarding_evening_window_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='working_timezone',
            field=models.CharField(default='America/New_York', max_length=64),
        ),
    ]
