# Generated by Django 5.2.14 on 2026-07-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_event_meeting_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='zoom_meeting_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
