# Generated by Django 5.2.14 on 2026-07-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_event_zoom_meeting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_panic',
            field=models.BooleanField(default=False),
        ),
    ]
