# Generated by Django 5.2.16 on 2026-08-01 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ref', models.CharField(blank=True, max_length=200)),
                ('session_ref', models.CharField(blank=True, max_length=200)),
                ('trigger_id', models.CharField(max_length=100)),
                ('tier', models.PositiveSmallIntegerField()),
                ('confidence', models.FloatField()),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('sla_deadline_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('in_review', 'In review'), ('escalated_to_clinical', 'Escalated to clinical'), ('resolved', 'Resolved'), ('false_positive', 'False positive')], default='open', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['tier', 'sla_deadline_at', '-confidence'],
            },
        ),
        migrations.CreateModel(
            name='EscalationTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=32)),
                ('to_status', models.CharField(max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalation_transitions', to=settings.AUTH_USER_MODEL)),
                ('escalation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='escalations.escalation')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='escalation',
            index=models.Index(fields=['status', 'tier', 'sla_deadline_at'], name='escalations_status_b58c2d_idx'),
        ),
    ]
