# Generated by Django 5.2.16 on 2026-08-01 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolutionMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='escalation',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalationtransition',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='resolution_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='escalations.resolutionmethod'),
        ),
        migrations.AddField(
            model_name='escalationtransition',
            name='resolution_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions', to='escalations.resolutionmethod'),
        ),
    ]
