# Generated by Django 5.2.14 on 2026-08-01 20:21

import django.db.models.deletion
import transcripts.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0008_event_is_panic'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_meeting_id', models.BigIntegerField(unique=True)),
                ('occurred_at', models.DateTimeField()),
                ('vtt_file', models.FileField(storage=transcripts.storage.select_transcript_storage, upload_to='transcripts/')),
                ('plain_text', models.TextField(blank=True)),
                ('duration_s', models.PositiveIntegerField(default=0)),
                ('grading_status', models.CharField(choices=[('pending', 'Pending'), ('graded', 'Graded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_transcripts', to=settings.AUTH_USER_MODEL)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_transcripts', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcripts', to='planner.event')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['created_at'], name='transcripts_created_409871_idx')],
            },
        ),
    ]
